### PR TITLE
fix to start motor and allow scan on RPLidar v2

### PR DESCRIPTION
**Pull request by redblade**
Hi,
digging into the v2 SDK it looks like a "start motor" command is necessary on v2 to enable the scan, so I added the necessary code.
Now I can control the RPM and the scan works great!

Could you please check the pull request and merge with your code?

Thanks
Francesco

### CODE REVIEW

**Comment by lessthanoptimal** [comment]
I'll check the pull request when I'm back from vacation in about a week.  Thanks!

**Comment by soblenes32** [comment]
It looks like the constant START_MOTOR was omitted from the checked-in code? It's not included in the official documentation, but going by the C++ SDK, the command value ought to be 0xF0. It would be helpful to include the pwm values 660 (default) and 1023 (max) for reference.

Also, I believe that this is only applicable when using the USB to UART accessory board. If controlling the RPLidar A2 via UART directly, then I believe that there's a separate pwm wire for the motor.

**Comment by jabrena** [comment]
Hi @redblade, can you add the constant in the file: `RpLidarLowLevelDriver`?

``` java
private static final byte START_MOTOR = (byte) 0xF0;
```

In my initial tests, the `RPLIDAR A2` now run nice with the PR.
Tomorrow, I will test `RPLIDAR A1` to check the backward compatibility.

@soblenes32, Do you know the constant to stop the motor?

The new `RPLIDAR A2` generates less noise than `RPLIDAR A1`, is pretty nice.

**Comment by soblenes32** [comment]
Yes, you should be able to assign it a PWM speed of 0 to stop it using the same command. I had to disable some of the startup checks to get it working reliably, but I can get data now at about 2000 samples per second. To get the full 4k samples per second, an implementation of the "express" setting will be needed, which has a completely different output format.

**Comment by jabrena** [comment]
Hi @soblenes32, you had reason, with this simple new method:

``` java
	/**
	 * Sends a stop motor command
	 */
	public void sendStopMotor() {
		sendPayLoad(START_MOTOR, 0);
	}
``` 

It is possible to stop the motor in a elegant way.

I have just tested in the same robot, both sensors without any conflict:

``` 
robot@brick1:~$ lsusb
Bus 001 Device 004: ID 2001:3308 D-Link Corp. DWA-121 802.11n Wireless N 150 Pico Adapter [Realtek RTL8188CUS]
Bus 001 Device 003: ID 10c4:ea60 Cygnal Integrated Products, Inc. CP210x UART Bridge / myAVR mySmartUSB light
Bus 001 Device 005: ID 10c4:ea60 Cygnal Integrated Products, Inc. CP210x UART Bridge / myAVR mySmartUSB light
Bus 001 Device 002: ID 05e3:0608 Genesys Logic, Inc. USB-2.0 4-Port HUB
Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
robot@brick1:~$ cd /dev
robot@brick1:/dev$ ls
autofs           fd       kmsg          memory_bandwidth    ptmx    snd     tty11  tty19  tty26  tty33  tty40  tty48  tty55  tty62  ttySU0   ttyprintk  vcs3   vcsa4
block            full     log           mmcblk0             pts     stderr  tty12  tty2   tty27  tty34  tty41  tty49  tty56  tty63  ttySU1   uinput     vcs4   vcsa5
bus              fuse     loop-control  mmcblk0p1           random  stdin   tty13  tty20  tty28  tty35  tty42  tty5   tty57  tty7   ttyUSB0  urandom    vcs5   vcsa6
char             hwrng    loop0         mmcblk0p2           rfkill  stdout  tty14  tty21  tty29  tty36  tty43  tty50  tty58  tty8   ttyUSB1  usbmon0    vcs6   watchdog
console          i2c-1    loop1         mqueue              rtc     tty     tty15  tty22  tty3   tty37  tty44  tty51  tty59  tty9   tty_in1  usbmon1    vcsa   watchdog0
cpu_dma_latency  initctl  loop2         network_latency     rtc0    tty0    tty16  tty23  tty30  tty38  tty45  tty52  tty6   ttyS0  tty_in2  vcs        vcsa1  zero
disk             input    loop3         network_throughput  serial  tty1    tty17  tty24  tty31  tty39  tty46  tty53  tty60  ttyS1  tty_in3  vcs1       vcsa2  zram0
fb0              kmem     mem           null                shm     tty10   tty18  tty25  tty32  tty4   tty47  tty54  tty61  ttyS2  tty_in4  vcs2       vcsa3
robot@brick1:/dev$ 
```

**Comment by jabrena** [comment]
Hi @soblenes32, when you say:

> To get the full 4k samples per second, an implementation of the "express" setting will be needed, which has a completely different output format.

What is your idea?

If you like, in order to close this `PR`, maybe is better to create a new issue about that topic.

Juan Antonio

**Comment by lessthanoptimal** [comment]
ok so just let me know what works and I'll merge it in. Should this pull request be merged in as is?

**Comment by jabrena** [comment]
Hi @lessthanoptimal, 

No, in the file: `RpLidarLowLevelDriver.java`, it is necessary to add the following constant to compile:

```
private static final byte START_MOTOR = (byte) 0xF0;
``` 

later the method to stop motor could improve the current solution:

``` 
         /**
	 * Sends a stop motor command
	 */
	public void sendStopMotor() {
		sendPayLoad(START_MOTOR, 0);
	}
```

I think that it is necessary to wait for a new update from @redblade 

Juan Antonio

**Review by redblade — COMMENTED** [review]
Sorry for my late reply, the file should now contain the suggested fix about START_MOTOR constant.

**Comment by redblade** [comment]
Hi all,
sorry for my late reply, I've updated the code with the missing constant

Francesco

2017-07-31 23:41 GMT+02:00 Juan Antonio Breña Moral <
notifications@github.com>:

**Comment by jabrena** [comment]
Nice work from @redblade and the comments from @soblenes32

**Pull request merged**
